{style src="addons/my_changes/mcs_general_less_rules.less"}
{style src="addons/my_changes/mcs_general_styles.css"}
{style src="addons/my_changes/mcs_general_styles.less"}
{style src="addons/my_changes/mcs_brands_page.css"}
{style src="addons/my_changes/mcs_brands_page.less"}
{style src="addons/my_changes/header/mcs_top_panel.css"}
{style src="addons/my_changes/header/mcs_header.css"}
{style src="addons/my_changes/header/mcs_header.less"}
{style src="addons/my_changes/header/mcs_top_menu.less"}
{style src="addons/my_changes/header/mcs_search_box.css"}
{style src="addons/my_changes/homepage/mcs_main_content.css"}
{style src="addons/my_changes/homepage/mcs_main_content.less"}
{style src="addons/my_changes/homepage/mcs_slider.css"}
{style src="addons/my_changes/homepage/mcs_slider.less"}
{style src="addons/my_changes/homepage/mcs_brand_scroller.css"}
{style src="addons/my_changes/homepage/mcs_brand_scroller.less"}
{style src="addons/my_changes/categories/mcs_i_category_view.css"}
{style src="addons/my_changes/categories/mcs_i_category_view.less"}
{style src="addons/my_changes/categories/mcs_products_grid.css"}
{style src="addons/my_changes/categories/mcs_products_grid.less"}
{style src="addons/my_changes/categories/mcs_side_menu.css"}
{style src="addons/my_changes/categories/mcs_side_menu.less"}
{style src="addons/my_changes/categories/mcs_sidebox.css"}
{style src="addons/my_changes/categories/mcs_sidebox.less"}
{style src="addons/my_changes/categories/mcs_sorting.less"}
{style src="addons/my_changes/products/mcs_product.css"}
{style src="addons/my_changes/products/mcs_product.less"}
{style src="addons/my_changes/pages/mcs_pages_side_menu.css"}
{style src="addons/my_changes/pages/mcs_pages_side_menu.less"}
{style src="addons/my_changes/mcs_labels/mcs_labels.css"}

{if $addons.mcs_framework.mcs_general_responsive_enable=='Y'}
	{style src="addons/my_changes/mcs_general_styles.resp.css"}
	{style src="addons/my_changes/header/mcs_top_panel.resp.css"}
    {style src="addons/my_changes/header/mcs_header.resp.css"}
	{style src="addons/my_changes/header/mcs_header.resp.less"}
    {style src="addons/my_changes/header/mcs_top_menu.resp.less"}
    {style src="addons/my_changes/header/mcs_search_box.resp.css"}
	{style src="addons/my_changes/homepage/mcs_main_content.resp.css"}
	{style src="addons/my_changes/homepage/mcs_slider.resp.css"}
	{style src="addons/my_changes/homepage/mcs_slider.resp.less"}
	{style src="addons/my_changes/categories/mcs_i_category_view.resp.css"}
    {style src="addons/my_changes/categories/mcs_sidebox.resp.css"}
    {style src="addons/my_changes/products/mcs_product.resp.css"}
{/if}
{literal}<style>.zxcasd{display:none;}</style>{/literal}